version: 1.6.1

# Site settings
title: Algolia for Magento
description: Power your Magento store with Algolia
baseurl: "/magento" # the subpath of your site, e.g. /blog/
twitter_username: algolia
github_username: algolia
host: 0.0.0.0

# Navigation
navigation:
 - text: Magento 1 Documentation
   url: /documentation/
 - text: Magento 2 Documentation
   url: /m2-documentation/
 - text: FAQ
   url: /faq/
 - text: About
   url: /about/

# Build settings
markdown: kramdown
kramdown:
  input: GFM

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

exclude:
  - headers

# Assets
sass:
  sass_dir: css
